# Generated by Django 3.2.7 on 2021-10-07 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_by', to=settings.AUTH_USER_MODEL)),
                ('hobby_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobby_acuvity', to='meet.interests')),
            ],
        ),
    ]
