# Generated by Django 3.2.7 on 2021-10-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(default='Message poster for more details', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
