# Generated by Django 3.2.7 on 2021-10-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
