# Generated by Django 3.2.7 on 2021-10-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='hobby',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_hobby', to='meet.interests'),
        ),
    ]
