# Generated by Django 3.2.7 on 2021-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_auto_20211017_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
