# Generated by Django 3.2.7 on 2021-10-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0011_room_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
