# Generated by Django 3.2.7 on 2021-10-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0012_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
