# Generated by Django 3.2.7 on 2021-10-29 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0013_auto_20211019_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_read', models.BooleanField(default=False)),
                ('notification_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_message', to=settings.AUTH_USER_MODEL)),
                ('notification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
