# Generated by Django 3.2.7 on 2021-10-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0014_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_message', to='meet.message'),
        ),
    ]
