# Generated by Django 3.2.7 on 2021-10-31 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0015_alter_notifications_notification_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.TextField()),
                ('connect_date', models.DateTimeField(auto_now_add=True)),
                ('connected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_user', to=settings.AUTH_USER_MODEL)),
                ('connection_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_room', to='meet.room')),
            ],
        ),
    ]
