# Generated by Django 3.2.7 on 2021-11-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0016_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userImage',
            field=models.ImageField(default='userimg/21/default-Image.png', upload_to='userimg/%y'),
        ),
    ]
