# Generated by Django 3.2.7 on 2021-11-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0017_user_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(),
        ),
    ]
